import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

const site = process.env.SITE_URL ?? 'https://pam.dev';
const base = process.env.BASE_PATH ?? '/';
const socialImage = new URL(`${base.replace(/\/$/, '')}/og-pam.png`, site).href;

export default defineConfig({
  site,
  base,
  integrations: [
    starlight({
      title: 'PAM',
      description: 'The persistent PHP runtime for servers, native mobile, and desktop applications.',
      logo: {
        src: './src/assets/pam-mark.svg',
        replacesTitle: true,
      },
      favicon: '/favicon.svg',
      head: [
        {
          tag: 'link',
          attrs: {
            rel: 'preconnect',
            href: 'https://fonts.googleapis.com',
          },
        },
        {
          tag: 'link',
          attrs: {
            rel: 'preconnect',
            href: 'https://fonts.gstatic.com',
            crossorigin: 'anonymous',
          },
        },
        {
          tag: 'meta',
          attrs: {
            name: 'theme-color',
            content: '#141411',
          },
        },
        { tag: 'meta', attrs: { property: 'og:image', content: socialImage } },
        { tag: 'meta', attrs: { property: 'og:image:width', content: '1200' } },
        { tag: 'meta', attrs: { property: 'og:image:height', content: '630' } },
        { tag: 'meta', attrs: { property: 'og:image:alt', content: 'PAM — one PHP runtime, every target' } },
        { tag: 'meta', attrs: { name: 'twitter:image', content: socialImage } },
        { tag: 'meta', attrs: { name: 'twitter:image:alt', content: 'PAM — one PHP runtime, every target' } },
      ],
      social: [
        { icon: 'github', label: 'GitHub', href: 'https://github.com/push-in/pam' },
      ],
      editLink: {
        baseUrl: 'https://github.com/push-in/pam-docs/edit/main/',
      },
      customCss: ['./src/styles/pam.css'],
      components: {
        Header: './src/components/PamHeader.astro',
      },
      sidebar: [
        {
          label: 'Start here',
          items: [
            { label: 'Introduction', slug: 'introduction' },
            { label: 'Installation', slug: 'getting-started/installation' },
            { label: 'Create your first app', slug: 'getting-started/first-app' },
            { label: 'Choose a target', slug: 'getting-started/choose-a-target' },
            { label: 'Capability catalog', slug: 'ecosystem' },
            { label: 'CLI & project console', slug: 'getting-started/cli' },
            { label: 'Project status', slug: 'project/status' },
            { label: 'Release 1.0.2', slug: 'project/release-1-0-2' },
          ],
        },
        {
          label: 'Server runtime',
          items: [
            { label: 'How PAM works', slug: 'runtime/how-pam-works' },
            { label: 'PHP Runtime Manager', slug: 'runtime/php-runtime-manager' },
            { label: 'HTTP applications', slug: 'runtime/http' },
            { label: 'Async I/O', slug: 'runtime/async-io' },
            { label: 'Durable workflows', slug: 'runtime/durable-workflows' },
            { label: 'Bootstrap snapshots', slug: 'runtime/bootstrap-snapshots' },
            { label: 'Cluster services', slug: 'runtime/cluster-services' },
            { label: 'Typed contracts', slug: 'runtime/typed-contracts' },
            { label: 'Supply-chain gate', slug: 'runtime/supply-chain' },
            { label: 'Sandbox, replay & trust', slug: 'runtime/security-replay-and-trust' },
            { label: 'WASI & typed RPC', slug: 'runtime/wasi-and-rpc' },
            { label: 'WebSockets', slug: 'runtime/websockets' },
            { label: 'Composer', slug: 'runtime/composer' },
            { label: 'Production', slug: 'runtime/production' },
            { label: 'Compatibility', slug: 'runtime/compatibility' },
          ],
        },
        {
          label: 'Laravel',
          items: [
            { label: 'Overview', slug: 'laravel/overview' },
            { label: 'Production platform', slug: 'laravel/production-platform' },
            { label: 'Request lifecycle', slug: 'laravel/request-lifecycle' },
            { label: 'Artisan & workers', slug: 'laravel/artisan-and-workers' },
            { label: 'Observability', slug: 'laravel/observability' },
            { label: 'Cloud & Forge', slug: 'laravel/cloud-and-forge' },
            { label: 'Autoscaling', slug: 'laravel/autoscaling' },
            { label: 'MCP automation', slug: 'laravel/mcp' },
            { label: 'Package matrix', slug: 'laravel/package-matrix' },
            { label: 'Package certification', slug: 'laravel/package-certification' },
            { label: 'Benchmark laboratory', slug: 'laravel/benchmarks' },
            { label: 'Reference application', slug: 'laravel/reference-application' },
            { label: 'Deploy Laravel', slug: 'laravel/deployment' },
          ],
        },
        {
          label: 'Native mobile',
          items: [
            { label: 'Overview', slug: 'native/overview' },
            { label: 'iOS renderer', slug: 'native/ios-renderer' },
            {
              label: 'Components',
              items: [
                { label: 'Overview', slug: 'native/components' },
                { label: 'Layout & views', slug: 'native/components/layout-and-views' },
                { label: 'Text, input & controls', slug: 'native/components/text-input-controls' },
                { label: 'Images & cache', slug: 'native/components/images-and-cache' },
                { label: 'Video & audio', slug: 'native/components/video-and-audio' },
                { label: 'Scroll & lists', slug: 'native/components/scroll-and-lists' },
                { label: 'Interaction & motion', slug: 'native/components/interaction-and-motion' },
                { label: 'Overlays & system UI', slug: 'native/components/overlays-and-system-ui' },
                { label: 'WebView', slug: 'native/components/webview' },
                { label: 'Custom native views', slug: 'native/native-views' },
              ],
            },
            { label: 'Responsive layout', slug: 'native/responsive-layout' },
            {
              label: 'Application core',
              items: [
                { label: 'State & lifecycle', slug: 'native/state-and-lifecycle' },
                { label: 'Component runtime', slug: 'native/component-runtime' },
                { label: 'Global store', slug: 'native/global-store' },
              ],
            },
            { label: 'Navigation', slug: 'native/navigation' },
            { label: 'Platform runtime', slug: 'native/platform-runtime' },
            { label: 'Platform capabilities', slug: 'native/capabilities' },
            { label: 'HTTP networking', slug: 'native/networking' },
            { label: 'Forms & validation', slug: 'native/forms' },
            { label: 'Files & media picker', slug: 'native/files-and-media' },
            { label: 'Hot reload', slug: 'native/hot-reload' },
            { label: 'Editor setup', slug: 'native/editor-tooling' },
            { label: 'Native views', slug: 'native/native-views' },
            { label: 'Plugin SDK', slug: 'native/plugins' },
            { label: 'DevTools', slug: 'native/devtools' },
            { label: 'Protocol & limits', slug: 'native/protocol' },
            { label: 'Migrate to Native 0.6', slug: 'native/migration-0-6' },
          ],
        },
        {
          label: 'Desktop',
          items: [
            {
              label: 'Start here',
              items: [
                { label: 'Overview', slug: 'desktop/overview' },
                { label: '5-minute tutorial', slug: 'desktop/quickstart' },
                { label: 'Mental model', slug: 'desktop/mental-model' },
                { label: 'PAM Desktop vs Electron', slug: 'desktop/electron-comparison' },
              ],
            },
            {
              label: 'Build',
              items: [
                { label: 'Convention-first authoring', slug: 'desktop/authoring' },
                { label: 'Commands & dependency injection', slug: 'desktop/commands-and-di' },
                { label: 'Windows, events & menus', slug: 'desktop/windows-events-and-menus' },
                { label: 'Desktop cookbook', slug: 'desktop/cookbook' },
                { label: 'Native capabilities', slug: 'desktop/capabilities' },
                { label: 'Native SQLite', slug: 'desktop/database' },
                { label: 'HTTP & streaming', slug: 'desktop/networking-and-streaming' },
                { label: 'Linux system integration', slug: 'desktop/system-integration' },
                { label: 'Native shell', slug: 'desktop/native-shell' },
                { label: 'Background jobs', slug: 'desktop/background-jobs' },
                { label: 'Execution & diagnostics', slug: 'desktop/execution-and-diagnostics' },
                { label: 'Application lifecycle', slug: 'desktop/lifecycle' },
                { label: 'Plugins', slug: 'desktop/plugins' },
                { label: 'Advanced API', slug: 'desktop/windows-and-commands' },
                { label: 'PHP API contracts', slug: 'desktop/api-contracts' },
              ],
            },
            {
              label: 'Ship & trust',
              items: [
                { label: 'Distribution', slug: 'desktop/distribution' },
                { label: 'Signed updates', slug: 'desktop/signed-updates' },
                { label: 'Security model', slug: 'desktop/security' },
                { label: 'Stability & support', slug: 'desktop/stability' },
              ],
            },
          ],
        },
        {
          label: 'Packages',
          items: [
            { label: 'Package ecosystem', slug: 'packages/overview' },
            { label: 'pushinbr/pam-api', slug: 'packages/api' },
            { label: 'pushinbr/pam-socket', slug: 'packages/socket' },
            { label: 'pushinbr/pam-psr-bridge', slug: 'packages/psr-bridge' },
            { label: 'pushinbr/pam-testing', slug: 'packages/testing' },
            { label: 'pushinbr/pam-core-api', slug: 'packages/core-api' },
            { label: 'PAM Native Nitro', slug: 'packages/native-nitro' },
            {
              label: 'Native integrations',
              items: [
                { label: 'Auth', slug: 'packages/native-auth' },
                { label: 'Background Transfer', slug: 'packages/native-background-transfer' },
                { label: 'Bluetooth', slug: 'packages/native-bluetooth' },
                { label: 'DevTools package', slug: 'packages/native-devtools' },
                { label: 'Feature Flags', slug: 'packages/native-feature-flags' },
                { label: 'Firebase', slug: 'packages/native-firebase' },
                { label: 'Health', slug: 'packages/native-health' },
                { label: 'Intents', slug: 'packages/native-intents' },
                { label: 'Laravel Sync', slug: 'packages/native-laravel-sync' },
                { label: 'Live Activities', slug: 'packages/native-live-activities' },
                { label: 'Maps', slug: 'packages/native-maps' },
                { label: 'Media & Camera', slug: 'packages/native-media' },
                { label: 'NFC', slug: 'packages/native-nfc' },
                { label: 'Observability', slug: 'packages/native-observability' },
                { label: 'Payments', slug: 'packages/native-payments' },
                { label: 'Plugin Kit', slug: 'packages/native-plugin-kit' },
                { label: 'Realtime', slug: 'packages/native-realtime' },
                { label: 'Scanner', slug: 'packages/native-scanner' },
                { label: 'Share Extension', slug: 'packages/native-share-extension' },
                { label: 'Subscriptions', slug: 'packages/native-subscriptions' },
                { label: 'Sync', slug: 'packages/native-sync' },
                { label: 'Testing', slug: 'packages/native-testing' },
                { label: 'Video', slug: 'packages/native-video' },
                { label: 'Widgets', slug: 'packages/native-widgets' },
              ],
            },
          ],
        },
        {
          label: 'Community',
          items: [
            { label: 'Contributing', slug: 'community/contributing' },
            { label: 'Roadmap', slug: 'community/roadmap' },
            { label: 'Documentation contract', slug: 'community/documentation' },
            { label: 'Security', slug: 'community/security' },
            { label: 'Licensing', slug: 'community/licensing' },
          ],
        },
      ],
    }),
  ],
});
